# Generated by Django 2.2.2 on 2019-06-16 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0004_auto_20190616_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nwa.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyedge',
            unique_together={('person', 'action')},
        ),
    ]
