# Generated by Django 2.2.2 on 2019-06-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwa', '0005_auto_20190616_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyedge',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='agencyedge',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='agencyedge',
            name='polarity',
        ),
        migrations.CreateModel(
            name='SocialEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('interaction', models.CharField(blank=True, max_length=20, null=True)),
                ('polarity', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nwa.Project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_edges', to='nwa.Person')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_edges', to='nwa.Person')),
            ],
            options={
                'verbose_name_plural': 'Social Edgelist',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
