# Generated by Django 2.2.2 on 2019-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0007_auto_20190616_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['action']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Actions categories'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization'], 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['name'], 'verbose_name_plural': 'Avatar powers'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['sector'], 'verbose_name_plural': 'Economy sectors'},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cognitive map variables'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='in_degree',
        ),
        migrations.RemoveField(
            model_name='person',
            name='degree',
        ),
        migrations.AlterField(
            model_name='agencyedge',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='agency_actor_in', to='nwa.Person'),
        ),
    ]
