# Generated by Django 2.2.2 on 2019-06-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0009_auto_20190617_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='agencyedge',
            unique_together={('person', 'action', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='mentaledge',
            unique_together={('person', 'source', 'target', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='poweredge',
            unique_together={('person', 'power', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='socialedge',
            unique_together={('source', 'target', 'project')},
        ),
    ]
