# Generated by Django 2.2.2 on 2019-06-24 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwa', '0010_auto_20190620_2228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentaledge',
            unique_together={('person', 'source', 'target', 'project', 'author')},
        ),
    ]
