# Generated by Django 2.2.2 on 2019-06-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0011_auto_20190624_2248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentaledge',
            unique_together=set(),
        ),
    ]
