# Generated by Django 2.2.2 on 2019-06-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0012_auto_20190624_2249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentaledge',
            unique_together={('person', 'source', 'target', 'project')},
        ),
    ]
