# Generated by Django 2.2.7 on 2019-11-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwa', '0014_auto_20191125_0121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentaledge',
            unique_together={('person', 'source', 'target', 'project')},
        ),
    ]
